### ISSUE TITLE
error whene i try to run 

### ISSUE THREAD

**Issue by tchach0** [EntySec/HatSploit#98]
└─$ hsf      
Traceback (most recent call last):
  File "/home/glitch/.local/bin/hsf", line 5, in <module>
    from hatsploit import cli
  File "/home/glitch/.local/lib/python3.10/site-packages/hatsploit/__init__.py", line 30, in <module>
    from .__main__ import HatSploit
  File "/home/glitch/.local/lib/python3.10/site-packages/hatsploit/__main__.py", line 33, in <module>
    from hatsploit.core.utils.api import API
  File "/home/glitch/.local/lib/python3.10/site-packages/hatsploit/core/utils/api.py", line 27, in <module>
    from flask import Flask
  File "/home/glitch/.local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/glitch/.local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3/dist-packages/itsdangerous/__init__.py)

**Comment by enty8080** [comment]
Hey, @tchach0 

I suggest you to upgrade `itsdangerous` package. As I can see, the problem is in dependencies.
